//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garden.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUser
    {
        public int loginID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int userTypeID { get; set; }
        public string loginName { get; set; }
        public string loginPassword { get; set; }
        public Nullable<int> loginFailCount { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string zipCode { get; set; }
        public string isTaskEmail { get; set; }
        public Nullable<bool> isOutOffice { get; set; }
        public Nullable<System.DateTime> PWExpireDate { get; set; }
        public System.DateTime createDate { get; set; }
        public string createBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string updateBy { get; set; }
        public string status { get; set; }
        public string isSetDefaultDivision { get; set; }
    }
}
